# Generated by Django 5.0.7 on 2025-09-11 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('time', models.TimeField(help_text='Локальное время выполнения')),
                ('is_pleasant', models.BooleanField(default=False)),
                ('reward', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'duration_seconds',
                    models.PositiveSmallIntegerField(default=60, help_text='Длительность ≤ 120 секунд'),
                ),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='через каждые N дней (1..7)')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'related_habit',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
